//! DNS Shield management and Steam Launch Options integration for VRChat.
//!
//! Provides:
//! 1. Active rules file sync (`~/.cache/lvr/shield_rules.txt` / `$XDG_RUNTIME_DIR/lvr/shield_rules.txt`).
//! 2. Installation and deployment of `liblvr_dns_shield.so`.
//! 3. Steam launch options formatting and 1-click install/remove via `crate::steam`.

use std::fs;
use std::path::PathBuf;
use anyhow::{Context, Result};

use crate::steam;
use super::{BlockState, active_domains};

pub const EMBEDDED_DNS_SHIELD_SO: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/liblvr_dns_shield.so"));

/// Returns default deployment path for the DNS shield shared library.
pub fn installed_shield_path() -> PathBuf {
    directories::ProjectDirs::from("", "", "lvr")
        .map(|dirs| dirs.data_dir().join("liblvr_dns_shield.so"))
        .unwrap_or_else(|| {
            directories::BaseDirs::new()
                .map(|b| b.home_dir().join(".local/share/lvr/liblvr_dns_shield.so"))
                .unwrap_or_else(|| PathBuf::from("/tmp/liblvr_dns_shield.so"))
        })
}

/// Returns paths where the active rules text file should be written for the shim.
pub fn shield_rules_paths() -> Vec<PathBuf> {
    let mut paths = Vec::new();
    if let Ok(runtime) = std::env::var("XDG_RUNTIME_DIR")
        && !runtime.trim().is_empty()
    {
        paths.push(PathBuf::from(runtime).join("lvr/shield_rules.txt"));
    }
    if let Some(dirs) = directories::ProjectDirs::from("", "", "lvr") {
        paths.push(dirs.cache_dir().join("shield_rules.txt"));
    } else if let Some(base) = directories::BaseDirs::new() {
        paths.push(base.cache_dir().join("lvr/shield_rules.txt"));
    }
    paths.push(PathBuf::from("/tmp/lvr_shield_rules.txt"));
    paths
}

/// Deploys the embedded `liblvr_dns_shield.so` to the user's data directory.
pub fn deploy_shield_library() -> Result<PathBuf> {
    let target = installed_shield_path();
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating directory for {}", target.display()))?;
    }
    fs::write(&target, EMBEDDED_DNS_SHIELD_SO)
        .with_context(|| format!("writing {}", target.display()))?;
    Ok(target)
}

/// Serializes and writes currently active blocked domain/wildcard rules into
/// a simple newline-separated text file read by `liblvr_dns_shield.so`.
pub fn sync_shield_rules(state: &BlockState) -> Result<()> {
    let lists = active_domains();
    let mut blocked_rules = Vec::new();

    // Iterate the raw map so we use the actual stored key (e.g. "Video" or
    // "Videos") and convert it to a BlockCategory for the is_blocked check.
    // This avoids a key mismatch where cat.name() returns "Videos" but the
    // VRChat remote config stores the list under "Video" (singular).
    for (key, domains) in &lists.domains {
        let cat = crate::domain_block::BlockCategory::from_name(key);
        if state.is_blocked(&cat) {
            for d in domains {
                let trimmed = d.trim().to_lowercase();
                if !trimmed.is_empty() {
                    blocked_rules.push(trimmed);
                }
            }
        }
    }

    blocked_rules.sort();
    blocked_rules.dedup();

    let mut content = String::with_capacity(blocked_rules.len() * 32);
    content.push_str("# LVR DNS Shield Rules (autogenerated)\n");
    for rule in blocked_rules {
        content.push_str(&rule);
        content.push('\n');
    }

    let bytes = content.as_bytes();

    for path in shield_rules_paths() {
        if let Some(parent) = path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        let _ = fs::write(&path, bytes);
    }

    Ok(())
}

// -----------------------------------------------------------------------------
// Steam Launch Options formatting & integration
// -----------------------------------------------------------------------------

/// Checks whether `liblvr_dns_shield.so` is present in VRChat's launch options.
pub fn is_shield_in_launch_options(launch_opts: &str) -> bool {
    launch_opts.contains("liblvr_dns_shield.so")
}

/// Formats the recommended full launch string with DNS shield enabled.
pub fn recommended_launch_options(existing: &str) -> String {
    let shield_path = installed_shield_path();
    let shield_str = shield_path.to_string_lossy();
    let preload_flag = format!("LD_PRELOAD=\"{shield_str}\"");

    if existing.trim().is_empty() {
        return format!("{preload_flag} %command%");
    }

    if existing.contains("liblvr_dns_shield.so") {
        return existing.trim().to_string();
    }

    if let Some(pos) = existing.find("%command%") {
        let before = existing[..pos].trim();
        let after = existing[pos..].trim();
        if before.is_empty() {
            format!("{preload_flag} {after}")
        } else {
            format!("{before} {preload_flag} {after}")
        }
    } else {
        format!("{preload_flag} {existing} %command%")
    }
}

/// Removes DNS shield LD_PRELOAD from a launch options string.
pub fn remove_shield_from_launch_options(existing: &str) -> String {
    let mut parts: Vec<&str> = existing.split_whitespace().collect();
    parts.retain(|part| !part.contains("liblvr_dns_shield.so") && !part.starts_with("LD_PRELOAD="));
    parts.join(" ")
}

/// Read the current Steam LaunchOptions string configured for VRChat.
pub fn read_steam_launch_options() -> Result<String> {
    steam::read_vrchat_launch_options()
}

/// Updates Steam's `localconfig.vdf` for VRChat with new launch options.
pub fn write_steam_launch_options(new_options: &str) -> Result<()> {
    steam::write_vrchat_launch_options(new_options)
}

/// Shut Steam down cleanly if running, wait for it to exit, then execute modification.
pub async fn set_steam_shield_enabled(enable: bool) -> Result<()> {
    let current = read_steam_launch_options().unwrap_or_default();
    let updated = if enable {
        deploy_shield_library()?;
        recommended_launch_options(&current)
    } else {
        remove_shield_from_launch_options(&current)
    };

    if current.trim() == updated.trim() {
        return Ok(());
    }

    // Shut down Steam if running so it doesn't overwrite VDF on exit
    let was_running = steam::steam_running();
    if was_running {
        steam::shutdown_steam().await?;
    }

    write_steam_launch_options(&updated)?;

    if was_running {
        steam::start_steam().await?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recommended_launch_options_appends_or_prepends_preload() {
        let existing = "--enable-avpro-in-proton %command% --foo";
        let rec = recommended_launch_options(existing);
        assert!(rec.contains("liblvr_dns_shield.so"));
        assert!(rec.contains("--enable-avpro-in-proton"));
        assert!(rec.contains("%command% --foo"));
    }

    #[test]
    fn remove_shield_strips_preload_flag() {
        let current = "LD_PRELOAD=\"/path/to/liblvr_dns_shield.so\" %command% --foo";
        let cleaned = remove_shield_from_launch_options(current);
        assert!(!cleaned.contains("liblvr_dns_shield.so"));
        assert_eq!(cleaned, "%command% --foo");
    }
}
