[package]
name = "lvr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
directories = "6.0.0"
eframe = "0.36.1"
egui = "0.36"
egui_extras = "0.36.1"
ksni = { version = "0.3.6", features = ["tokio"] }
libc = "0.2.189"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.140"
shell-words = "1.1.1"
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "sync", "process", "signal"] }
toml = "1.1.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
zbus = "5.19.0"

[build-dependencies]
cc = "1.2"
serde_json = "1.0"


[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[lints.clippy]
all = { level = "warn", priority = -1 }
correctness = { level = "deny", priority = -1 }
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
too_many_lines = "warn"

